#!/bin/bash
echo "Gammaup v1.1 - Boost your screen's display brightness."
echo "This software is licensed under GPL v3 and is provided as-is with no guarantee of suitability for a particular purpose. Use at your own risk."
echo ""

# VARIABLES
BLUE_BOLD=`echo -en "\e[1;34m"`
NORMAL=`echo -en "\e[0m"`

# PROMPT
echo "${BLUE_BOLD}Set your brightness level: (default is 0)${NORMAL}"
echo "0 - normal (1.0)"
echo "1 - moderate (1.25)"
echo "2 - high (1.5)"
echo "3 - extreme (1.75)"
echo "i - show current status"
echo "q - quit"
echo ""
read -p "> " ANSWER0
case "$ANSWER0" in
	0 | "")
		xgamma -rgamma 1.0 -ggamma 1.0 -bgamma 1.0
		echo "Gamma set to standard values."
		;;
	1)
		xgamma -rgamma 1.25 -ggamma 1.25 -bgamma 1.25
		echo "Gamma set to moderate values."
		;;
	2 | 11)
		xgamma -rgamma 1.5 -ggamma 1.5 -bgamma 1.5
		echo "Gamma set to high values."
		;;
	3 | 111)
		xgamma -rgamma 1.75 -ggamma 1.75 -bgamma 1.75
		echo "Gamma set to extreme values."
		;;
	[iI])
		echo "Current gamma:"
		xgamma
		;;
	*)
		echo "Aborted."
		exit 0
		;;
esac
